ARG OPENWRT_VERSION=24.10.3
ARG OPENWRT_PLATFORM
ARG PROFILE
ARG PACKAGES
ARG DISABLED_SERVICES
ARG ROOTFS_PARTSIZE

ARG IMAGE_NAME=ghcr.io/openwrt/imagebuilder:${OPENWRT_PLATFORM}-v${OPENWRT_VERSION}

FROM $IMAGE_NAME AS builder
ARG PROFILE ROOTFS_PARTSIZE PACKAGES DISABLED_SERVICES OPENWRT_PLATFORM OPENWRT_VERSION 
ENV PROFILE=${PROFILE} ROOTFS_PARTSIZE=${ROOTFS_PARTSIZE} PACKAGES=${PACKAGES} DISABLED_SERVICES=${DISABLED_SERVICES} OPENWRT_PLATFORM=${OPENWRT_PLATFORM} OPENWRT_VERSION=${OPENWRT_VERSION}
WORKDIR /builder
RUN [ "make", "image", "PROFILE:=${PROFILE}", "ROOTFS_PARTSIZE:=${ROOTFS_PARTSIZE}", "PACKAGES:=${PACKAGES}", "DISABLED_SERVICES:=${DISABLED_SERVICES}" ]
RUN mkdir ./output
RUN find ./build_dir/ -name "*-${PROFILE}-*" -type f -exec cp {} ./output \;

FROM alpine
WORKDIR /output
COPY --from=builder /builder/output/* ./
VOLUME [ "/out" ]
RUN mkdir -p /out
CMD ["/bin/cp", "-R", "-f", ".", "/out"]