
services:
  main:
    build:
      args:
        OPENWRT_VERSION: 24.10.2
        #OPENWRT_PLATFORM: rockchip-armv8
        #PROFILE: friendlyarm_nanopi-r5c
        OPENWRT_PLATFORM: rockchip-armv8
        PROFILE: friendlyarm_nanopi-r3s
        PACKAGES: base-files ca-bundle -dnsmasq dropbear e2fsprogs firewall4 fstools kmod-gpio-button-hotplug kmod-nft-offload libc libgcc libustream-mbedtls logd mkf2fs mtd netifd nftables odhcp6c odhcpd-ipv6only opkg partx-utils ppp ppp-mod-pppoe procd-ujail uboot-envtools uci uclient-fetch urandom-seed urngd kmod-r8169 luci luci-app-acme acme-acmesh-dnsapi luci-proto-wireguard luci-app-attendedsysupgrade nano dnscrypt-proxy2 kmod-bonding luci-app-bcp38 luci-app-bcp38 nut parted losetup resize2fs blkid kmod-vrf owut collectd collectd-mod-cpu collectd-mod-cpufreq collectd-mod-df collectd-mod-interface collectd-mod-load collectd-mod-memory collectd-mod-network collectd-mod-ntpd collectd-mod-sensors collectd-mod-smart collectd-mod-snmp collectd-mod-sqm collectd-mod-thermal collectd-mod-uptime dnsmasq-full kmod-rtc-pcf8563 hwclock i2c-tools pv
        DISABLED_SERVICES: ""
        ROOTFS_PARTSIZE: 512
      context: .
      dockerfile: ./Dockerfile
      
    image: main
    volumes:
      - type: bind
        source: ./out
        target: /out
        bind:
          create_host_path: true
    
    

