
services:
  main:
    build:
      args:
        OPENWRT_VERSION: 24.10.3
        OPENWRT_PLATFORM: rockchip-armv8
        PROFILE: friendlyarm_nanopi-r5c
        PACKAGES: base-files ca-bundle dnsmasq dropbear e2fsprogs firewall4 fstools kmod-gpio-button-hotplug kmod-nft-offload libc libgcc libustream-mbedtls logd mkf2fs mtd netifd nftables odhcp6c odhcpd-ipv6only opkg partx-utils ppp ppp-mod-pppoe procd-ujail uboot-envtools uci uclient-fetch urandom-seed urngd kmod-r8169 wpad-basic-mbedtls iwinfo luci owut luci-app-attendedsysupgrade
        DISABLED_SERVICES: ""
        ROOTFS_PARTSIZE: 512
      context: .
      dockerfile: ./Dockerfile
      
    image: main
    volumes:
      - type: bind
        source: ./out
        target: /out
        bind:
          create_host_path: true
    
    

